import { BaseGuardian } from './BaseGuardian';
import { AnalysisReport } from '../types';
export declare class UXGuardian extends BaseGuardian {
    private uxMetrics;
    private wcagGuidelines;
    performSpecializedAnalysis(): Promise<AnalysisReport>;
    private analyzeAccessibility;
    private analyzeUsability;
    private analyzeUXPerformance;
    private analyzeInclusion;
    private analyzeResponsiveDesign;
    private analyzeCognitiveLoad;
    private analyzeEmotionalResonance;
    private calculateUXMetrics;
    private generateUXSummary;
    private calculateConfidenceScore;
    private determineWCAGComplianceLevel;
    private calculateUserImpact;
    private analyzeColorContrast;
    private analyzeKeyboardNavigation;
    private analyzeAltText;
    private analyzeSemanticStructure;
    private analyzeUserFlows;
    private analyzeFormUsability;
    private analyzeNavigation;
    private analyzeSystemFeedback;
    private analyzeLoadingPerception;
    private analyzeInteractivityDelay;
    private analyzeAnimationPerformance;
    private analyzeCulturalInclusivity;
    private analyzeAbilityInclusion;
    private analyzeDigitalDivide;
    private analyzeBreakpoints;
    private analyzeTouchTargets;
    private analyzeOrientationSupport;
    private analyzeVisualComplexity;
    private analyzeInformationOverload;
    private analyzeConsistency;
    private analyzeBrandPersonality;
    private analyzeMicrointeractions;
    private analyzeDesignEmpathy;
    private calculateOverallUXScore;
    private calculateUXPhilosophyAlignment;
    private predictUserSatisfaction;
    private calculateInclusivityIndex;
    private initializeMetrics;
}
export default UXGuardian;
