global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Configuración para scrapear métricas del backend de GAMIFIER
  - job_name: 'gamifier-backend'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/prometheus-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Configuración para scrapear métricas de Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuración para scrapear métricas de Redis (si tiene exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Configuración para scrapear métricas de PostgreSQL (si tiene exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s 