databases:
  - name: coomunity-db
    databaseName: coomunity
    user: coomunity_user
    plan: free

services:
  #--------------------------------
  # Redis Cache
  #--------------------------------
  - type: redis
    name: coomunity-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  #--------------------------------
  # Backend - NestJS
  #--------------------------------
  - type: web
    name: coomunity-backend
    runtime: docker
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier3.5
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    dockerCommand: "npm run start:prod:migrate"
    envVars:
      - key: PORT
        value: 3002
      - fromDatabase:
          name: coomunity-db
          property: connectionString
        key: DATABASE_URL
      - fromService:
          type: redis
          name: coomunity-redis
          property: connectionString
        key: REDIS_URL
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  #--------------------------------
  # Frontend - SuperApp (Vite)
  #--------------------------------
  - type: web
    name: coomunity-superapp
    runtime: node
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier3.5
    rootDir: Demo/apps/superapp-unified
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npx serve -s dist"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: coomunity-backend
          property: url
      - key: VITE_BASE_URL
        fromService:
          type: web
          name: coomunity-superapp
          property: url
      - key: VITE_NETWORK_API_URL
        fromService:
          type: web
          name: coomunity-backend
          property: url
      - key: VITE_NETWORK_BASE_URL
        fromService:
          type: web
          name: coomunity-superapp
          property: url
      - key: VITE_ENABLE_MOCK_AUTH
        value: "false"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
      - key: VITE_BETA_TRACKING
        value: "false"
      - key: VITE_GA_TRACKING_ID
        value: "G-XXXXXXXXXX"
      - key: VITE_HOTJAR_ID
        value: "0000000"
