databases:
  - name: coomunity-db
    databaseName: coomunity
    user: coomunity_user
    plan: free

services:
  # Redis Cache
  - type: redis
    name: coomunity-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  # Backend - NestJS (Docker, recomendado)
  - type: web
    name: beforenostr-backend
    plan: free
    runtime: docker
    repo: https://github.com/kvn3toj/beforenostr
    dockerContext: .
    dockerfilePath: ./Dockerfile.backend
    healthCheck:
      path: /health
    envVars:
      - key: PORT
        value: 3002
      - fromDatabase:
          name: coomunity-db
          property: connectionString
        key: DATABASE_URL
      - key: REDIS_URL
        value: 'redis://red-d1ain6fdiees73ddnpi0:6379'
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - backend/**
        - prisma/**
        - package.json
        - package-lock.json
      ignoredPaths:
        - backend/**/*.test.ts

  # Frontend - SuperApp (Vite)
  - type: web
    name: coomunity-superapp
    plan: free
    runtime: node
    repo: https://github.com/kvn3toj/beforenostr
    branch: main
    rootDir: Demo/apps/superapp-unified
    buildCommand: 'npm install --legacy-peer-deps && npm run build'
    startCommand: 'npx serve -s dist'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: 'https://god-backend-j4b6.onrender.com'
      - key: VITE_BASE_URL
        value: 'https://coomunity-superapp.onrender.com'
      - key: VITE_NETWORK_API_URL
        value: 'https://god-backend-j4b6.onrender.com'
      - key: VITE_NETWORK_BASE_URL
        value: 'https://coomunity-superapp.onrender.com'
      - key: VITE_ENABLE_MOCK_AUTH
        value: 'false'
      - key: VITE_ENABLE_ANALYTICS
        value: 'true'
      - key: VITE_BETA_TRACKING
        value: 'false'
      - key: VITE_GA_TRACKING_ID
        value: 'G-XXXXXXXXXX'
      - key: VITE_HOTJAR_ID
        value: '0000000'
    buildFilter:
      paths:
        - Demo/apps/superapp-unified/**
        - shared/**
