services:
  - type: web
    name: superapp
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm run build:render
    startCommand: npm run start:render
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier2.0
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: coomunity-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: coomunity-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        value: "https://superapp-peach.vercel.app,http://localhost:3001"

  - type: redis
    name: coomunity-redis
    region: oregon
    plan: free

databases:
  - name: coomunity-postgres
    databaseName: coomunity
    user: coomunity_user
    region: oregon
    plan: free
