services:
  # 🚀 CoomÜnity Backend - NestJS API
  - type: web
    name: coomunity-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    plan: starter
    region: oregon
    branch: main
    buildCommand: echo "Building with Docker"
    startCommand: node dist/main.js

    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: coomunity-postgres
          property: connectionString
      - key: REDIS_URL
        value: redis://red-abc123:6379
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://coomunity-superapp.vercel.app
      - key: API_BASE_URL
        value: https://coomunity-backend.onrender.com

    # Health check endpoint
    healthCheckPath: /health

databases:
  # 🗄️ PostgreSQL Database
  - name: coomunity-postgres
    databaseName: coomunity_prod
    user: coomunity_user
    plan: starter
    region: oregon
    postgresMajorVersion: "15"


