databases:
  - name: coomunity-db
    databaseName: coomunity
    user: coomunity_user
    plan: free

services:
  #--------------------------------
  # Redis Cache
  #--------------------------------
  - type: redis
    name: coomunity-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  #--------------------------------
  # Backend - NestJS
  #--------------------------------
  - type: web
    name: coomunity-backend
    plan: free
    runtime: docker
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier3.5
    dockerfilePath: ./backend/Dockerfile.simple
    healthCheckPath: /health
    dockerCommand: "npm run start:prod"
    envVars:
      - key: PORT
        value: 3002
      - fromDatabase:
          name: coomunity-db
          property: connectionString
        key: DATABASE_URL
      - fromService:
          type: redis
          name: coomunity-redis
          property: connectionString
        key: REDIS_URL
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://coomunity-superapp.onrender.com,https://coomunity-admin.onrender.com"
      - key: BCRYPT_ROUNDS
        value: "12"

  #--------------------------------
  # Frontend - SuperApp (Vite)
  #--------------------------------
  - type: web
    name: coomunity-superapp
    plan: free
    runtime: node
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier3.5
    rootDir: Demo/apps/superapp-unified
    buildCommand: "npm install --legacy-peer-deps && npm run build:prod"
    startCommand: "npx serve -s dist -p $PORT"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: "https://coomunity-backend.onrender.com"
      - key: VITE_BASE_URL
        value: "https://coomunity-superapp.onrender.com"
      - key: VITE_NETWORK_API_URL
        value: "https://coomunity-backend.onrender.com"
      - key: VITE_APP_ENV
        value: "production"
      - key: VITE_ENABLE_MOCK_AUTH
        value: "false"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"

  #--------------------------------
  # Admin Frontend - Gamifier Admin
  #--------------------------------
  - type: web
    name: coomunity-admin
    plan: free
    runtime: node
    repo: https://github.com/kvn3toj/beforenostr
    branch: gamifier3.5
    rootDir: apps/admin-frontend
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npx serve -s dist -p $PORT"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: "https://coomunity-backend.onrender.com"
      - key: VITE_BASE_URL
        value: "https://coomunity-admin.onrender.com"
      - key: VITE_APP_ENV
        value: "production"
