import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsEnum, IsUrl } from 'class-validator';
import { MeritType } from '@prisma/client'; // Assuming MeritType enum is generated by Prisma

export class CreateMeritDto {
  @ApiProperty({ description: 'The name of the merit' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({ description: 'A unique slug for the merit' })
  @IsString()
  @IsNotEmpty()
  slug: string;

  @ApiProperty({ description: 'A description of the merit', required: false })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiProperty({ description: 'The symbol representing the merit (e.g., COIN, XP)', required: false })
  @IsString()
  @IsOptional()
  symbol?: string;

  @ApiProperty({ description: 'The type of merit (e.g., CURRENCY, EXPERIENCE, ACHIEVEMENT)', enum: MeritType })
  @IsEnum(MeritType)
  type: MeritType;

  @ApiProperty({ description: 'URL to the icon representing the merit', required: false })
  @IsUrl()
  @IsOptional()
  iconUrl?: string;
} 