%% @backgroundColor(#ffffff)
graph LR
    A[Fase 1: Unificación Backend]
    B[Diseño y Setup Inicial]
    C[Desarrollo de Módulos]
    D[RBAC]
    E[API REST]
    F[Infraestructura y Despliegue]
    G[Listo para Frontend]

    A --> B --> C --> D --> E --> F --> G 