groups:
  - name: coomunity_technical_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is above 500ms"

      - alert: BackendDown
        expr: up{job="coomunity-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "CoomÜnity Backend is down"
          description: "Backend NestJS is not responding"

  - name: coomunity_philosophical_alerts
    rules:
      - alert: LowAyniScore
        expr: ayni_balance_score < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Ayni balance is low"
          description: "Reciprocity score has dropped below 70%"

      - alert: BienComunDecline
        expr: bien_comun_contributions_rate < 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Bien Común contributions declining"
          description: "Community contributions rate is below 50%"
